language: r
r:
  - devel
#  - release
dist: trusty
sudo: required
cache: packages
env:
  global:
    - _R_CRAN_CHECK_INCOMING_=false
r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"
r_check_revdep: false
warnings_are_errors: false


apt_packages:
  - libcurl4-openssl-dev
  - libxml2-dev
  - default-jre
  - default-jdk

r_binary_packages:
 - testthat
r_packages:
  - devtools
r_github_packages:
  - jimhester/covr
  - jeroenooms/curl


# report to codecov
after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/ppdb.R"), quiet = FALSE)'

# report to maintainer
notifications:
  email:
    recipients:
    - eduardszoecs@gmail.com
    on_success: change
    on_failure: change

