# Workflow derived from
# https://github.com/r-lib/actions/blob/v2-branch/examples/check-standard.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 12 * * 0"

name: Run tests without {vcr}

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      VCR_TURN_OFF: true

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat

      - name: run tests
        run: |
          testthat::test_local()